### ISSUE TITLE
2.0: Pull hashes from YAML.

### ISSUE THREAD

**Issue by keith-gardner** [BrantaOps/branta-windows#93]
# Local YAML

- In offline mode, or if server is unavailable, Branta will lean on local yaml file.
- When branta (later) pulls an updated YAML from the server, write the new yaml file to disk for future offline sessions. 
- Store timestamp of last update at the top of the each yaml file:
  - `timestamp: <time here>`
- Lastly, find somewhere on the UI to show user when the last time the hashes were refreshed.

# YAML Format:
- [Installer hashes](https://github.com/BrantaOps/branta-windows/blob/main/Branta/Assets/InstallerHashes.yaml) are a basic `string:string` dictionary:
```
# BlockstreamGreen. Standard SHA 256 from manifest.
# BlockstreamGreen 1.2.9
"6c28ed9f08c2bfdd1a9ccb5da26ab27549d3d95ac791e013c3316264a0b7a2eb":  "BlockstreamGreen_Windows_x86_64.zip"
"1b8589bc997016087ba27ef28f2026626834c91af525ca88bd3841bafcbe4c06":  "BlockstreamGreen_MacOS_x86_64.zip"
"f7bbc3333012ffd8a3512ede7415169329b4010cfe9f96ae6e1a92268236a52e":  "BlockstreamGreen-x86_64.AppImage"
"19e24095367acf1eb94818c4d67ccabc9e86f5e128edbb05f586bd6bae844822":  "BlockstreamGreen_Linux_x86_64.tar.gz"

# BlockstreamGreen 1.2.8
"47d394ef3beaf96b77f2210e796be0a41c70afb9109b3b069655abeacdc485d0": "BlockstreamGreen_Windows_x86_64.zip"

# ...
```

- [Checksums](https://github.com/BrantaOps/branta-windows/blob/main/Branta/Assets/CheckSums.yaml) are nested:
```
blockstreamGreen:
    "2.0.3":
        sha256: "03af53cf9bd6e3a768c4c3b8d46a1035bbcea328cd970d80f174f9b82ca6495a"
        date: 2024-03-28 00:00:00.00
    "1.2.9":
        md5: "c21fcd79baeccc5cbc06101a12747322"
        date: 2024-01-01 00:00:00.00
    "1.2.8":
        md5: "1080a79948f976c682604bca429f6e14"
        date: 2024-01-01 00:00:00.00
    "1.2.7":
        md5: "6f452462209bb191386339a6b4dfef10"
        date: 2024-01-01 00:00:00.00

ledger:
    "2.77.2": 
        sha256: "cbe1bc7a105dde2d9ad4182c8e51fa3bffb7b25fd2e0ed19c8560ee55f9498b7"
        date: 2024-02-23 00:00:00.00
```

# Note
- `Sparrow` is the only wallet we need to support for this update.
- The design should require minimal changes to add a second wallet
